export const SET_PAGE_VALUE = 'SET_PAGE_VALUE';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const LOAD_USER = 'LOAD_USER';
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
